version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "daily"
    automerged_updates:
    - match:
        dependency_name: "Fody"
        update_type: "all"
    - match:
        dependency_name: "*.Fody"
        update_type: "all"
    - match:
        dependency_name: "Catel.*"
        update_type: "all"
    - match:
        dependency_name: "Orc.*"
        update_type: "all"
    - match:
        dependency_name: "Orchestra.*"
        update_type: "all"
    - match:
        dependency_name: "Blorc.*"
        update_type: "all"