name: dependabot-cake
on:
  workflow_dispatch:
  schedule:
    # run everyday at 6
    - cron:  '0 6 * * *'

jobs:
  dependabot-cake:
    runs-on: ubuntu-latest # linux, because this is a docker-action
    steps:
      - name: Check and update cake dependencies
        uses: nils-org/dependabot-cake-action@v1
        with:
          # Where to look for cake files to check for dependency upgrades.
          # The directory is relative to the repository's root.
          # Multiple paths can be provided by splitting them with a new line.
          # Example:
          #   directory: |
          #     /path/to/first/module
          #     /path/to/second/module
          # Default: "/"
          directory: "/deployment/cake"